import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import {
  generateFiles,
  type GeneratedFile,
  isInsideDir,
  type LocaleCache,
  parseTranslationFile,
  syncOutput,
} from "../src/codegen.js";
import { CodegenError } from "../src/errors.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.dirname(here);
const basicFixture = path.join(here, "fixtures", "basic");

const createdDirs: string[] = [];

function tmpDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "i18n-codegen-test-"));
  createdDirs.push(dir);
  return dir;
}

function writeResources(root: string, files: Record<string, string>): string {
  const srcDir = path.join(root, "resources");
  fs.mkdirSync(srcDir, { recursive: true });
  for (const [name, content] of Object.entries(files)) {
    fs.writeFileSync(path.join(srcDir, name), content);
  }
  return srcDir;
}

/** Wraps content in the marker header that identifies plugin-owned files. */
function generated(body: string): string {
  return `/* Generated by vite-plugin-i18n-codegen — do not edit manually */\n${body}`;
}

afterEach(() => {
  for (const dir of createdDirs.splice(0)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

describe("generateFiles", () => {
  it("generates the exact expected files for the basic fixture", () => {
    const outDir = tmpDir();
    const files = generateFiles({
      srcDir: path.join(basicFixture, "resources"),
      outDir,
    });

    const byName = new Map(files.map((file) => [path.basename(file.path), file]));
    expect([...byName.keys()].sort()).toEqual(["de.ts", "en_US.ts", "index.ts"]);

    for (const name of ["de.ts", "en_US.ts", "index.ts"]) {
      const expected = fs.readFileSync(path.join(basicFixture, "expected", name), "utf8");
      expect(byName.get(name)?.content).toBe(expected);
    }
  });

  it("matches the example locale files byte-for-byte", () => {
    const files = generateFiles({
      srcDir: path.join(basicFixture, "resources"),
      outDir: tmpDir(),
    });
    const exampleDir = path.join(here, "fixtures", "basic", "expected");

    for (const name of ["de.ts", "en_US.ts"]) {
      const file = files.find((f) => path.basename(f.path) === name);
      const expected = fs.readFileSync(path.join(exampleDir, name), "utf8");
      expect(file?.content).toBe(expected);
    }
  });

  it("dedupes repeated placeholders and keeps first-appearance order", () => {
    const srcDir = writeResources(tmpDir(), {
      "en.json": JSON.stringify({ greet: "Hi, {name} and {name} and {other} {name}" }),
    });
    const [file] = generateFiles({ srcDir, outDir: tmpDir() });
    expect(file.content).toContain(
      "greet: (name: string, other: string) => `Hi, ${name} and ${name} and ${other} ${name}`,",
    );
  });

  it("escapes backticks, backslashes and newlines in template literals", () => {
    const srcDir = writeResources(tmpDir(), {
      "en.json": JSON.stringify({
        code: "Use `code`, ${x} and back\\slash",
        lines: "first\nsecond\tthird",
      }),
    });
    const [file] = generateFiles({ srcDir, outDir: tmpDir() });
    expect(file.content).toContain(
      "code: (x: string) => `Use \\`code\\`, $${x} and back\\\\slash`,",
    );
    expect(file.content).toContain("lines: () => `first\\nsecond\\tthird`,");
  });

  it("errors on invalid JSON and carries the offending file id", () => {
    const srcDir = writeResources(tmpDir(), { "bad.json": "{ not json " });
    let caught: unknown;
    try {
      generateFiles({ srcDir, outDir: tmpDir() });
    } catch (err) {
      caught = err;
    }
    expect(caught).toBeInstanceOf(CodegenError);
    expect((caught as CodegenError).id).toBe(path.join(srcDir, "bad.json"));
    expect((caught as CodegenError).message).toMatch(/not valid JSON/);
  });

  it("errors on nested values", () => {
    const srcDir = writeResources(tmpDir(), {
      "en.json": JSON.stringify({ menu: { home: "Home" } }),
    });
    expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
      /"menu" in en.json must be a string/,
    );
  });

  it("errors when a locale is missing a key from the reference", () => {
    const srcDir = writeResources(tmpDir(), {
      "de.json": JSON.stringify({ welcome: "Willkommen", hello: "Hallo" }),
      "en.json": JSON.stringify({ welcome: "Welcome" }),
    });
    expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
      /en.json is missing translation key "hello"/,
    );
  });

  it("errors when placeholders differ between locales", () => {
    const srcDir = writeResources(tmpDir(), {
      "de.json": JSON.stringify({ welcome: "Willkommen, {name}!" }),
      "en.json": JSON.stringify({ welcome: "Welcome, {fullName}!" }),
    });
    expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
      /Placeholders for "welcome"/,
    );
  });

  it("errors on invalid placeholder names", () => {
    const srcDir = writeResources(tmpDir(), {
      "en.json": JSON.stringify({ welcome: "Welcome, {first name}!" }),
    });
    expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
      /Invalid placeholder "\{first name\}"/,
    );
  });

  it("errors on unmatched braces", () => {
    const srcDir = writeResources(tmpDir(), {
      "en.json": JSON.stringify({ welcome: "Welcome, {name" }),
    });
    expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
      /Unmatched "\{" or "\}"/,
    );
  });

  it("errors when the source directory has no JSON resources", () => {
    const srcDir = writeResources(tmpDir(), {});
    expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
      /No \.json translation resources found/,
    );
  });

  it("errors when the source directory does not exist", () => {
    const missing = path.join(tmpDir(), "nope");
    expect(() => generateFiles({ srcDir: missing, outDir: tmpDir() })).toThrowError(
      /does not exist/,
    );
  });

  it("allows locale names with only letters, numbers and underscores", () => {
    const srcDir = writeResources(tmpDir(), {
      "en1.json": JSON.stringify({ hello: "Hello" }),
      "en_US.json": JSON.stringify({ hello: "Hello" }),
    });
    const files = generateFiles({ srcDir, outDir: tmpDir() });
    const index = files.find((file) => path.basename(file.path) === "index.ts");
    expect(index?.content).toContain('export type Locale = "en1" | "en_US";');
    expect(index?.content).toContain(
      "export const dictionary: Dictionary = { en1: en1, en_US: en_US };",
    );
  });

  it("orders locales by code point so output does not depend on the host locale", () => {
    const srcDir = writeResources(tmpDir(), {
      "En.json": JSON.stringify({ hello: "Hello" }),
      "_1.json": JSON.stringify({ hello: "Hello" }),
      "de.json": JSON.stringify({ hello: "Hallo" }),
      "en1.json": JSON.stringify({ hello: "Hello" }),
    });
    const files = generateFiles({ srcDir, outDir: tmpDir() });
    const index = files.find((file) => path.basename(file.path) === "index.ts");
    expect(index?.content).toContain('export type Locale = "En" | "_1" | "de" | "en1";');
  });

  it("errors when a locale name contains a hyphen", () => {
    const srcDir = writeResources(tmpDir(), {
      "de.json": JSON.stringify({ hello: "Hallo" }),
      "en-US.json": JSON.stringify({ hello: "Hello" }),
    });
    expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
      /Locale names may only contain letters, numbers, and underscores/,
    );
  });

  it("prefixes reserved words when used as identifiers", () => {
    const srcDir = writeResources(tmpDir(), {
      "if.json": JSON.stringify({ hello: "If" }),
    });
    const files = generateFiles({ srcDir, outDir: tmpDir() });
    const index = files.find((file) => path.basename(file.path) === "index.ts");
    expect(index?.content).toContain('import _if from "./if.js";');
    expect(index?.content).toContain("export const dictionary: Dictionary = { if: _if };");
  });

  it("uses explicit dictionary keys when locale names are not shorthand-safe", () => {
    const srcDir = writeResources(tmpDir(), {
      "123.json": JSON.stringify({ hello: "Hello" }),
    });
    const files = generateFiles({ srcDir, outDir: tmpDir() });
    const index = files.find((file) => path.basename(file.path) === "index.ts");
    expect(index?.content).toContain('import _123 from "./123.js";');
    expect(index?.content).toContain("export const dictionary: Dictionary = { 123: _123 };");
  });

  it("quotes dictionary keys that are valid locale names but not object property names", () => {
    const srcDir = writeResources(tmpDir(), {
      "1a.json": JSON.stringify({ hello: "Hello" }),
    });
    const files = generateFiles({ srcDir, outDir: tmpDir() });
    const index = files.find((file) => path.basename(file.path) === "index.ts");
    expect(index?.content).toContain('import _1a from "./1a.js";');
    expect(index?.content).toContain('export const dictionary: Dictionary = { "1a": _1a };');
  });

  it("errors when two locales sanitize to the same identifier", () => {
    const srcDir = writeResources(tmpDir(), {
      "1.json": JSON.stringify({ hello: "A" }),
      "_1.json": JSON.stringify({ hello: "B" }),
    });
    expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
      /same import identifier "_1"/,
    );
  });

  it("quotes keys that are not valid identifiers", () => {
    const srcDir = writeResources(tmpDir(), {
      "en.json": JSON.stringify({ "my key": "Hello" }),
    });
    const files = generateFiles({ srcDir, outDir: tmpDir() });
    const localeFile = files.find((file) => path.basename(file.path) === "en.ts");
    const index = files.find((file) => path.basename(file.path) === "index.ts");
    expect(localeFile?.content).toContain('"my key": () => `Hello`,');
    expect(index?.content).toContain('"my key": () => string;');
  });

  it("imports the type barrel type-only and with an explicit extension", () => {
    const srcDir = writeResources(tmpDir(), { "en.json": JSON.stringify({ hello: "Hello" }) });
    const files = generateFiles({ srcDir, outDir: tmpDir() });
    const localeFile = files.find((file) => path.basename(file.path) === "en.ts");
    const index = files.find((file) => path.basename(file.path) === "index.ts");
    expect(localeFile?.content).toContain('import type { Translations } from "./index.js";');
    expect(index?.content).toContain('import en from "./en.js";');
  });

  it.each(["class", "new", "await", "let"])(
    "errors when a placeholder uses the reserved word %s",
    (word) => {
      const srcDir = writeResources(tmpDir(), {
        "en.json": JSON.stringify({ hello: `Hi {${word}}` }),
      });
      expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
        new RegExp(`Placeholder "\\{${word}\\}".+is reserved`),
      );
    },
  );

  it.each(["eval", "arguments"])(
    "errors when a placeholder is named %s, which is illegal in strict mode",
    (word) => {
      const srcDir = writeResources(tmpDir(), {
        "en.json": JSON.stringify({ hello: `Hi {${word}}` }),
      });
      expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
        new RegExp(`Placeholder "\\{${word}\\}".+is reserved`),
      );
    },
  );

  it("errors on a __proto__ translation key instead of emitting a prototype setter", () => {
    const srcDir = writeResources(tmpDir(), {
      "en.json": '{"__proto__":"boom","ok":"fine"}',
    });
    expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
      /"__proto__" in en\.json cannot be used as a translation key/,
    );
  });

  it("sanitizes locale names that are illegal binding names", () => {
    const srcDir = writeResources(tmpDir(), { "eval.json": JSON.stringify({ hello: "Hello" }) });
    const files = generateFiles({ srcDir, outDir: tmpDir() });
    const index = files.find((file) => path.basename(file.path) === "index.ts");
    expect(index?.content).toContain('import _eval from "./eval.js";');
    expect(index?.content).toContain("export const dictionary: Dictionary = { eval: _eval };");
  });

  it.each(["0123", "09"])("quotes the numeric locale key %s to avoid an octal literal", (name) => {
    const srcDir = writeResources(tmpDir(), {
      [`${name}.json`]: JSON.stringify({ hello: "Hello" }),
    });
    const files = generateFiles({ srcDir, outDir: tmpDir() });
    const index = files.find((file) => path.basename(file.path) === "index.ts");
    expect(index?.content).toContain(
      `export const dictionary: Dictionary = { "${name}": _${name} };`,
    );
  });

  it("gives every locale the same signature when a translation reorders placeholders", () => {
    const srcDir = writeResources(tmpDir(), {
      "de.json": JSON.stringify({ welcome: "Willkommen, {name}, in {place}!" }),
      "en.json": JSON.stringify({ welcome: "{place} welcomes you, {name}!" }),
    });
    const files = generateFiles({ srcDir, outDir: tmpDir() });
    const de = files.find((file) => path.basename(file.path) === "de.ts");
    const en = files.find((file) => path.basename(file.path) === "en.ts");
    const index = files.find((file) => path.basename(file.path) === "index.ts");
    expect(de?.content).toContain(
      "welcome: (name: string, place: string) => `Willkommen, ${name}, in ${place}!`,",
    );
    expect(en?.content).toContain(
      "welcome: (name: string, place: string) => `${place} welcomes you, ${name}!`,",
    );
    expect(index?.content).toContain("welcome: (name: string, place: string) => string;");
  });

  it("orders parameters alphabetically, not by appearance", () => {
    const srcDir = writeResources(tmpDir(), {
      "en.json": JSON.stringify({ hello: "Hi {zeta} then {alpha}" }),
    });
    const [file] = generateFiles({ srcDir, outDir: tmpDir() });
    expect(file.content).toContain(
      "hello: (alpha: string, zeta: string) => `Hi ${zeta} then ${alpha}`,",
    );
  });

  it("keeps signatures stable when a locale sorting before the reference is added", () => {
    const root = tmpDir();
    const before = generateFiles({
      srcDir: writeResources(root, {
        "en.json": JSON.stringify({ welcome: "Welcome, {name}, to {place}!" }),
      }),
      outDir: tmpDir(),
    });
    const srcDir = writeResources(root, {
      // Sorts before en.json and mentions the placeholders in the other order.
      "cs.json": JSON.stringify({ welcome: "{place} vítá {name}!" }),
    });
    const after = generateFiles({ srcDir, outDir: tmpDir() });

    const signatureOf = (files: GeneratedFile[]): string | undefined =>
      files
        .find((file) => path.basename(file.path) === "index.ts")
        ?.content.split("\n")
        .find((line) => line.includes("welcome:"));
    expect(signatureOf(after)).toBe(signatureOf(before));
    expect(signatureOf(after)).toBe("  welcome: (name: string, place: string) => string;");
  });

  it("still errors when the placeholder sets differ between locales", () => {
    const srcDir = writeResources(tmpDir(), {
      "de.json": JSON.stringify({ welcome: "Willkommen, {name}, in {place}!" }),
      "en.json": JSON.stringify({ welcome: "Welcome, {name}!" }),
    });
    expect(() => generateFiles({ srcDir, outDir: tmpDir() })).toThrowError(
      /Placeholders for "welcome"/,
    );
  });

  it("escapes remaining control characters as unicode escapes", () => {
    const srcDir = writeResources(tmpDir(), {
      "en.json": JSON.stringify({ bell: "a\u0007b\u007f" }),
    });
    const [file] = generateFiles({ srcDir, outDir: tmpDir() });
    expect(file.content).toContain("bell: () => `a\\u0007b\\u007f`,");
  });

  it("reuses cached parses until mtime or size changes", () => {
    const srcDir = writeResources(tmpDir(), { "en.json": JSON.stringify({ hello: "Hello" }) });
    const cache: LocaleCache = new Map();
    const outDir = tmpDir();

    const first = generateFiles({ srcDir, outDir }, cache);
    expect(cache.size).toBe(1);
    const cached = cache.get(path.join(srcDir, "en.json"))?.locale;
    expect(generateFiles({ srcDir, outDir }, cache)[0].content).toBe(first[0].content);
    expect(cache.get(path.join(srcDir, "en.json"))?.locale).toBe(cached);

    fs.writeFileSync(path.join(srcDir, "en.json"), JSON.stringify({ hello: "Hello again" }));
    fs.utimesSync(path.join(srcDir, "en.json"), new Date(), new Date(Date.now() + 2000));
    expect(generateFiles({ srcDir, outDir }, cache)[0].content).toContain("Hello again");
  });

  it("drops cache entries for deleted locales", () => {
    const srcDir = writeResources(tmpDir(), {
      "en.json": JSON.stringify({ hello: "Hello" }),
      "de.json": JSON.stringify({ hello: "Hallo" }),
    });
    const cache: LocaleCache = new Map();
    const outDir = tmpDir();
    generateFiles({ srcDir, outDir }, cache);
    expect(cache.size).toBe(2);

    fs.rmSync(path.join(srcDir, "de.json"));
    generateFiles({ srcDir, outDir }, cache);
    expect([...cache.keys()]).toEqual([path.join(srcDir, "en.json")]);
  });
});

describe("generated output validity", () => {
  it("type-checks under strict mode and verbatimModuleSyntax", () => {
    const root = tmpDir();
    const srcDir = writeResources(root, {
      "de.json": JSON.stringify({
        welcome: "Willkommen, {name}, in {place}!",
        "my key": "Ein `Backtick`, ein $ und ein \\ und {count}",
        greeting: "Zeile1\nZeile2\tEnde",
        if: "Reserviertes Wort als Schlüssel",
      }),
      "en_US.json": JSON.stringify({
        welcome: "{place} welcomes you, {name}!",
        "my key": "A `backtick`, a $ and a \\ and {count}",
        greeting: "line1\nline2\tend",
        if: "Reserved word as key",
      }),
    });
    const outDir = path.join(root, "i18n");
    syncOutput(generateFiles({ srcDir, outDir }), new Map(), outDir);

    fs.writeFileSync(
      path.join(root, "package.json"),
      JSON.stringify({ name: "generated-check", type: "module", version: "0.0.0" }),
    );
    fs.writeFileSync(
      path.join(root, "tsconfig.json"),
      JSON.stringify({
        compilerOptions: {
          target: "ESNext",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          noEmit: true,
          verbatimModuleSyntax: true,
          skipLibCheck: true,
        },
        include: ["i18n"],
      }),
    );

    const tsc = path.join(repoRoot, "node_modules", ".bin", "tsc");
    const result = spawnSync(tsc, ["-p", path.join(root, "tsconfig.json")], { encoding: "utf8" });
    expect(`${result.stdout}${result.stderr}`.trim()).toBe("");
    expect(result.status).toBe(0);
  }, 60_000);
});

describe("isInsideDir", () => {
  const dir = path.join(path.sep, "project", "src", "i18n", "resources");

  it("accepts files directly inside and nested below the directory", () => {
    expect(isInsideDir(dir, path.join(dir, "en.json"))).toBe(true);
    expect(isInsideDir(dir, path.join(dir, "nested", "en.json"))).toBe(true);
  });

  it("rejects sibling directories that merely share a name prefix", () => {
    expect(isInsideDir(dir, path.join(`${dir}-backup`, "en.json"))).toBe(false);
    expect(isInsideDir(dir, `${dir}.json`)).toBe(false);
  });

  it("rejects the directory itself, parents and unrelated paths", () => {
    expect(isInsideDir(dir, dir)).toBe(false);
    expect(isInsideDir(dir, path.dirname(dir))).toBe(false);
    expect(isInsideDir(dir, path.join(path.sep, "elsewhere", "en.json"))).toBe(false);
  });
});

describe("parseTranslationFile", () => {
  it("captures locale name, identifier and ordered params", () => {
    const srcDir = writeResources(tmpDir(), {
      "en_US.json": JSON.stringify({ hello: "Hello, {firstName} {lastName}!" }),
    });
    const parsed = parseTranslationFile(path.join(srcDir, "en_US.json"));
    expect(parsed.locale).toBe("en_US");
    expect(parsed.identifier).toBe("en_US");
    expect(parsed.entries[0].params).toEqual(["firstName", "lastName"]);
    expect(parsed.entries[0].template).toBe("Hello, ${firstName} ${lastName}!");
  });
});

describe("syncOutput", () => {
  it("writes new files, skips unchanged ones and removes stale files", () => {
    const outDir = tmpDir();
    const previous = new Map<string, string>();

    const files: Array<{ path: string; content: string }> = [
      { path: path.join(outDir, "a.ts"), content: "one\n" },
      { path: path.join(outDir, "b.ts"), content: "two\n" },
    ];
    expect(syncOutput(files, previous)).toHaveLength(2);
    expect(fs.readFileSync(files[0].path, "utf8")).toBe("one\n");

    files[1] = { ...files[1], content: "two!\n" };
    const changed = syncOutput(files, previous);
    expect(changed).toEqual([files[1].path]);
    expect(fs.readFileSync(files[1].path, "utf8")).toBe("two!\n");
    expect(fs.readFileSync(files[0].path, "utf8")).toBe("one\n");

    syncOutput([files[0]], previous);
    expect(fs.existsSync(files[1].path)).toBe(false);
  });

  it("does not rewrite files that already match on disk after a restart", () => {
    const outDir = tmpDir();
    const target = path.join(outDir, "a.ts");
    const files = [{ path: target, content: generated("one\n") }];

    syncOutput(files, new Map(), outDir);
    const firstMtime = fs.statSync(target).mtimeMs;

    // A fresh process starts with empty bookkeeping; the content is unchanged, so
    // nothing should be written (no needless watcher/HMR churn).
    expect(syncOutput(files, new Map(), outDir)).toEqual([]);
    expect(fs.statSync(target).mtimeMs).toBe(firstMtime);
  });

  it("removes generated files orphaned while the process was not running", () => {
    const outDir = tmpDir();
    const orphan = path.join(outDir, "fr.ts");
    const keep = path.join(outDir, "en.ts");
    fs.writeFileSync(orphan, generated("stale\n"));
    fs.writeFileSync(keep, generated("current\n"));

    const changed = syncOutput(
      [{ path: keep, content: generated("current\n") }],
      new Map(),
      outDir,
    );
    expect(changed).toEqual([orphan]);
    expect(fs.existsSync(orphan)).toBe(false);
    expect(fs.existsSync(keep)).toBe(true);
  });

  it("leaves unrelated files in outDir alone", () => {
    const outDir = tmpDir();
    const handWritten = path.join(outDir, "helpers.ts");
    fs.writeFileSync(handWritten, "export const t = 1;\n");

    syncOutput(
      [{ path: path.join(outDir, "en.ts"), content: generated("x\n") }],
      new Map(),
      outDir,
    );
    expect(fs.existsSync(handWritten)).toBe(true);
  });

  it("refuses to overwrite a file it did not generate", () => {
    const outDir = tmpDir();
    const target = path.join(outDir, "index.ts");
    fs.writeFileSync(target, "export const mine = true;\n");

    let caught: unknown;
    try {
      syncOutput([{ path: target, content: generated("theirs\n") }], new Map(), outDir);
    } catch (err) {
      caught = err;
    }
    expect(caught).toBeInstanceOf(CodegenError);
    expect((caught as CodegenError).message).toMatch(/Refusing to overwrite/);
    expect((caught as CodegenError).id).toBe(target);
    expect(fs.readFileSync(target, "utf8")).toBe("export const mine = true;\n");
  });

  it("does not write anything when one file in the batch is blocked", () => {
    const outDir = tmpDir();
    const blocked = path.join(outDir, "index.ts");
    const other = path.join(outDir, "en.ts");
    fs.writeFileSync(blocked, "export const mine = true;\n");

    expect(() =>
      syncOutput(
        [
          { path: other, content: generated("a\n") },
          { path: blocked, content: generated("b\n") },
        ],
        new Map(),
        outDir,
      ),
    ).toThrowError(/Refusing to overwrite/);
    expect(fs.existsSync(other)).toBe(false);
  });
});
