/* eslint-disable */
/* prettier-ignore */
/* Generated by vite-plugin-i18n-codegen — do not edit manually */

import { Translations } from ".";

export default {
  welcome: (name: string) => `Willkommen, ${name}!`,
  hello: (firstName: string, lastName: string) => `Hallo, ${firstName} ${lastName}!`,
  greeting: () => `Hallo zusammen!`,
} satisfies Translations;
