/* eslint-disable */
/* prettier-ignore */
/* Generated by vite-plugin-i18n-codegen — do not edit manually */

import { Translations } from ".";

export default {
  welcome: (name: string) => `Welcome, ${name}!`,
  hello: (firstName: string, lastName: string) => `Hello, ${firstName} ${lastName}!`,
  greeting: () => `Hi there!`,
} satisfies Translations;
