/* eslint-disable */
/* prettier-ignore */
/* Generated by vite-plugin-i18n-codegen — do not edit manually */

import de from "./de";
import en_US from "./en_US";

export type Locale = "de" | "en_US";
export type Translations = {
  welcome: (name: string) => string;
  hello: (firstName: string, lastName: string) => string;
  greeting: () => string;
};
export type Dictionary = Record<Locale, Translations>;

export const dictionary: Dictionary = { de, en_US };
