import fs from "node:fs";
import path from "node:path";
import { CodegenError } from "./errors.js";

const HEADER = [
  "/* eslint-disable */",
  "/* prettier-ignore */",
  "/* Generated by vite-plugin-i18n-codegen — do not edit manually */",
].join("\n");

const JS_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const RESERVED_WORDS = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "implements",
  "import",
  "in",
  "instanceof",
  "interface",
  "let",
  "new",
  "null",
  "package",
  "private",
  "protected",
  "public",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "await",
]);

export interface CodegenOptions {
  srcDir: string;
  outDir: string;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface TranslationEntry {
  key: string;
  params: string[];
  template: string;
}

export interface ParsedLocale {
  filePath: string;
  locale: string;
  identifier: string;
  entries: TranslationEntry[];
}

export function generateFiles(options: CodegenOptions): GeneratedFile[] {
  const { srcDir, outDir } = options;
  if (!fs.existsSync(srcDir)) {
    throw new CodegenError(`Translation source directory does not exist: ${srcDir}`);
  }

  const sourceFiles = fs
    .readdirSync(srcDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
    .map((entry) => path.join(srcDir, entry.name))
    .sort((a, b) => a.localeCompare(b));

  if (sourceFiles.length === 0) return [];

  const locales = sourceFiles.map((filePath) => parseTranslationFile(filePath));

  validateIdentifiers(locales);
  const reference = locales[0];
  validateParity(locales, reference);

  const output: GeneratedFile[] = locales.map((locale) => ({
    path: path.join(outDir, `${locale.locale}.ts`),
    content: buildLocaleFile(locale),
  }));
  output.push({
    path: path.join(outDir, "index.ts"),
    content: buildIndexFile(locales, reference),
  });
  return output;
}

export function parseTranslationFile(filePath: string): ParsedLocale {
  let raw: string;
  try {
    raw = fs.readFileSync(filePath, "utf8");
  } catch (err) {
    throw new CodegenError(`Unable to read "${filePath}": ${(err as Error).message}`, filePath);
  }

  let data: unknown;
  try {
    data = JSON.parse(raw);
  } catch (err) {
    throw new CodegenError(
      `${path.basename(filePath)} is not valid JSON: ${(err as Error).message}`,
      filePath,
    );
  }

  if (typeof data !== "object" || data === null || Array.isArray(data)) {
    throw new CodegenError(
      `${path.basename(filePath)} must contain a flat object of string translations`,
      filePath,
    );
  }

  const entries: TranslationEntry[] = [];
  for (const [key, value] of Object.entries(data)) {
    if (typeof value !== "string") {
      throw new CodegenError(
        `"${key}" in ${path.basename(filePath)} must be a string (only flat string translations are supported, found ${typeof value})`,
        filePath,
      );
    }
    entries.push(parseEntry(key, value, filePath));
  }

  return {
    filePath,
    locale: path.basename(filePath, ".json"),
    identifier: toIdentifier(path.basename(filePath, ".json")),
    entries,
  };
}

export function syncOutput(files: GeneratedFile[], previous: Map<string, string>): string[] {
  const changed: string[] = [];
  const next = new Map<string, string>();

  for (const file of files) {
    next.set(file.path, file.content);
    if (previous.get(file.path) !== file.content) {
      fs.mkdirSync(path.dirname(file.path), { recursive: true });
      fs.writeFileSync(file.path, file.content);
      changed.push(file.path);
    }
  }

  for (const stalePath of previous.keys()) {
    if (!next.has(stalePath)) {
      fs.rmSync(stalePath, { force: true });
      changed.push(stalePath);
    }
  }

  previous.clear();
  for (const [filePath, content] of next) {
    previous.set(filePath, content);
  }
  return changed;
}

function parseEntry(key: string, value: string, filePath: string): TranslationEntry {
  const params: string[] = [];
  const parts: string[] = [];
  const placeholderRe = /\{([A-Za-z_$][A-Za-z0-9_$]*)\}|\{[^{}]*\}/g;
  let last = 0;

  for (const match of value.matchAll(placeholderRe)) {
    const index = match.index ?? 0;
    const literal = value.slice(last, index);
    validateBraceFree(key, literal, filePath);
    parts.push(escapeTemplateLiteral(literal));
    if (match[1] !== undefined) {
      const param = match[1];
      if (!params.includes(param)) params.push(param);
      parts.push(`\${${param}}`);
    } else {
      throw new CodegenError(
        `Invalid placeholder "${match[0]}" in "${key}" (${path.basename(filePath)}). Placeholders must be valid identifiers, e.g. {name}`,
        filePath,
      );
    }
    last = index + match[0].length;
  }

  const tail = value.slice(last);
  validateBraceFree(key, tail, filePath);
  parts.push(escapeTemplateLiteral(tail));

  return { key, params, template: parts.join("") };
}

function validateBraceFree(key: string, literal: string, filePath: string): void {
  if (literal.includes("{") || literal.includes("}")) {
    throw new CodegenError(
      `Unmatched "{" or "}" in "${key}" (${path.basename(filePath)})`,
      filePath,
    );
  }
}

function escapeTemplateLiteral(value: string): string {
  return (
    value
      .replace(/\\/g, "\\\\")
      .replace(/`/g, "\\`")
      .replace(/\$\{/g, "\\${")
      .replace(/\r/g, "\\r")
      .replace(/\n/g, "\\n")
      .replace(/\t/g, "\\t")
      // eslint-disable-next-line no-control-regex
      .replace(/[\u0000-\u001f\u007f]/g, (char) => {
        return `\\u${char.charCodeAt(0).toString(16).padStart(4, "0")}`;
      })
  );
}

function isValidIdentifier(name: string): boolean {
  return JS_IDENTIFIER.test(name) && !RESERVED_WORDS.has(name);
}

function toIdentifier(name: string): string {
  if (isValidIdentifier(name)) return name;
  const parts = name.split(/[^A-Za-z0-9_$]+/).filter(Boolean);
  const camel = parts
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
  if (isValidIdentifier(camel)) return camel;
  return camel.length > 0 ? `_${camel}` : "_";
}

function validateIdentifiers(locales: ParsedLocale[]): void {
  const seen = new Set<string>();
  for (const locale of locales) {
    if (seen.has(locale.identifier)) {
      throw new CodegenError(
        `Multiple locale files map to the same import identifier "${locale.identifier}"`,
      );
    }
    seen.add(locale.identifier);
  }
}

function validateParity(locales: ParsedLocale[], reference: ParsedLocale): void {
  const referenceByName = new Map(reference.entries.map((entry) => [entry.key, entry]));
  const referenceName = path.basename(reference.filePath);

  for (const locale of locales) {
    const own = new Map(locale.entries.map((entry) => [entry.key, entry]));
    for (const key of referenceByName.keys()) {
      const entry = own.get(key);
      if (entry === undefined) {
        throw new CodegenError(
          `${path.basename(locale.filePath)} is missing translation key "${key}" present in ${referenceName}`,
          locale.filePath,
        );
      }
      const expected = referenceByName.get(key)?.params ?? [];
      if (!sameParams(expected, entry.params)) {
        throw new CodegenError(
          `Placeholders for "${key}" in ${path.basename(locale.filePath)} (${formatParams(entry.params)}) do not match ${referenceName} (${formatParams(expected)})`,
          locale.filePath,
        );
      }
    }
    for (const key of own.keys()) {
      if (!referenceByName.has(key)) {
        throw new CodegenError(
          `"${key}" in ${path.basename(locale.filePath)} is not present in ${referenceName}`,
          locale.filePath,
        );
      }
    }
  }
}

function sameParams(a: string[], b: string[]): boolean {
  return a.length === b.length && a.every((param, index) => param === b[index]);
}

function formatParams(params: string[]): string {
  return params.length > 0 ? `{${params.join(", ")}}` : "(none)";
}

function keyLabel(key: string): string {
  return isValidIdentifier(key) ? key : JSON.stringify(key);
}

function buildLocaleFile(locale: ParsedLocale): string {
  const lines = [
    HEADER,
    "",
    'import { Translations } from ".";',
    "",
    "export default {",
    ...locale.entries.map((entry) => {
      const params = entry.params.map((param) => `${param}: string`).join(", ");
      return `  ${keyLabel(entry.key)}: (${params}) => \`${entry.template}\`,`;
    }),
    "} satisfies Translations;",
    "",
  ];
  return lines.join("\n");
}

function buildIndexFile(locales: ParsedLocale[], reference: ParsedLocale): string {
  const lines = [
    HEADER,
    "",
    ...locales.map((locale) => `import ${locale.identifier} from "./${locale.locale}";`),
    "",
    `export type Locale = ${locales.map((locale) => JSON.stringify(locale.locale)).join(" | ")};`,
    "export type Translations = {",
    ...reference.entries.map((entry) => {
      const params = entry.params.map((param) => `${param}: string`).join(", ");
      return `  ${keyLabel(entry.key)}: (${params}) => string;`;
    }),
    "};",
    "export type Dictionary = Record<Locale, Translations>;",
    "",
    `export const dictionary: Dictionary = { ${locales.map((locale) => locale.identifier).join(", ")} };`,
    "",
  ];
  return lines.join("\n");
}
