import fs from "node:fs";
import path from "node:path";
import { CodegenError, PLUGIN_NAME } from "./errors.js";

const GENERATED_MARKER = `Generated by ${PLUGIN_NAME}`;

const HEADER = [
  "/* eslint-disable */",
  "/* prettier-ignore */",
  `/* ${GENERATED_MARKER} — do not edit manually */`,
].join("\n");

/** Bytes inspected when deciding whether an existing file was produced by this plugin. */
const HEADER_SCAN_BYTES = 512;

const JS_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const LOCALE_NAME = /^[A-Za-z0-9_]+$/;
const NUMERIC_KEY = /^[0-9]+$/;
const PLACEHOLDER = /\{([A-Za-z_$][A-Za-z0-9_$]*)\}|\{[^{}]*\}/g;
// Matching control characters is the point: they are escaped out of the output.
// eslint-disable-next-line no-control-regex
const NEEDS_ESCAPE = /[\\`\u0000-\u001f\u007f]/g;

const ESCAPE_MAP: Record<string, string> = {
  "\\": "\\\\",
  "`": "\\`",
  "\r": "\\r",
  "\n": "\\n",
  "\t": "\\t",
};

const RESERVED_WORDS = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "implements",
  "import",
  "in",
  "instanceof",
  "interface",
  "let",
  "new",
  "null",
  "package",
  "private",
  "protected",
  "public",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "await",
]);

/** Not reserved words, but illegal as binding names in strict mode (generated files are modules). */
const RESTRICTED_BINDINGS = new Set(["eval", "arguments"]);

/** Setting this as an object literal key mutates the prototype instead of defining a property. */
const FORBIDDEN_KEY = "__proto__";

export interface CodegenOptions {
  srcDir: string;
  outDir: string;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface TranslationEntry {
  key: string;
  /** Placeholder names in order of first appearance within this locale's value. */
  params: string[];
  template: string;
}

export interface ParsedLocale {
  filePath: string;
  locale: string;
  identifier: string;
  entries: TranslationEntry[];
  /** Same entries, indexed by translation key. */
  entriesByKey: Map<string, TranslationEntry>;
}

export interface LocaleCacheEntry {
  mtimeMs: number;
  size: number;
  locale: ParsedLocale;
}

/**
 * Keyed by absolute file path. Lets repeated runs (a dev-server watch loop) skip
 * re-reading and re-parsing files that have not changed.
 */
export type LocaleCache = Map<string, LocaleCacheEntry>;

/**
 * True when `target` sits inside `dir`. A plain `startsWith` check would also
 * match sibling paths that merely share a prefix (`resources` / `resources-old`).
 */
export function isInsideDir(dir: string, target: string): boolean {
  const relative = path.relative(dir, target);
  return relative.length > 0 && !relative.startsWith("..") && !path.isAbsolute(relative);
}

export function generateFiles(options: CodegenOptions, cache?: LocaleCache): GeneratedFile[] {
  const { srcDir, outDir } = options;
  const sourceFiles = readSourceFiles(srcDir);

  if (sourceFiles.length === 0) {
    throw new CodegenError(`No .json translation resources found in: ${srcDir}`);
  }

  const locales = sourceFiles.map((filePath) => parseTranslationFile(filePath, cache));
  if (cache) pruneCache(cache, sourceFiles);

  validateIdentifiers(locales);
  const reference = locales[0];
  validateParity(locales, reference);

  const output: GeneratedFile[] = locales.map((locale) => ({
    path: path.join(outDir, `${locale.locale}.ts`),
    content: buildLocaleFile(locale),
  }));
  output.push({
    path: path.join(outDir, "index.ts"),
    content: buildIndexFile(locales, reference),
  });
  return output;
}

export function parseTranslationFile(filePath: string, cache?: LocaleCache): ParsedLocale {
  const locale = path.basename(filePath, ".json");
  validateLocaleName(locale, filePath);

  // Stat before reading: a write racing this read leaves the cached mtime older
  // than the content, so the next run re-parses instead of serving stale output.
  const stats = cache ? statOrUndefined(filePath) : undefined;
  if (stats) {
    const hit = cache?.get(filePath);
    if (hit && hit.mtimeMs === stats.mtimeMs && hit.size === stats.size) return hit.locale;
  }

  let raw: string;
  try {
    raw = fs.readFileSync(filePath, "utf8");
  } catch (err) {
    throw new CodegenError(`Unable to read "${filePath}": ${(err as Error).message}`, filePath);
  }

  let data: unknown;
  try {
    data = JSON.parse(raw);
  } catch (err) {
    throw new CodegenError(
      `${path.basename(filePath)} is not valid JSON: ${(err as Error).message}`,
      filePath,
    );
  }

  if (typeof data !== "object" || data === null || Array.isArray(data)) {
    throw new CodegenError(
      `${path.basename(filePath)} must contain a flat object of string translations`,
      filePath,
    );
  }

  const entries: TranslationEntry[] = [];
  const entriesByKey = new Map<string, TranslationEntry>();
  for (const [key, value] of Object.entries(data)) {
    if (key === FORBIDDEN_KEY) {
      throw new CodegenError(
        `"${FORBIDDEN_KEY}" in ${path.basename(filePath)} cannot be used as a translation key`,
        filePath,
      );
    }
    if (typeof value !== "string") {
      throw new CodegenError(
        `"${key}" in ${path.basename(filePath)} must be a string (only flat string translations are supported, found ${typeof value})`,
        filePath,
      );
    }
    const entry = parseEntry(key, value, filePath);
    entries.push(entry);
    entriesByKey.set(key, entry);
  }

  const parsed: ParsedLocale = {
    filePath,
    locale,
    identifier: toIdentifier(locale),
    entries,
    entriesByKey,
  };

  if (cache && stats) {
    cache.set(filePath, { mtimeMs: stats.mtimeMs, size: stats.size, locale: parsed });
  }
  return parsed;
}

export function syncOutput(
  files: GeneratedFile[],
  previous: Map<string, string>,
  outDir?: string,
): string[] {
  const changed: string[] = [];
  const next = new Map<string, string>();
  const pending: GeneratedFile[] = [];
  // With nothing tracked in memory yet, disk is the only source of truth for
  // what this plugin wrote during an earlier process.
  const coldStart = previous.size === 0;

  for (const file of files) {
    next.set(file.path, file.content);
    if (previous.get(file.path) === file.content) continue;

    const onDisk = readFileIfExists(file.path);
    if (onDisk === file.content) continue;
    if (onDisk !== undefined && !previous.has(file.path) && !isGeneratedContent(onDisk)) {
      throw new CodegenError(
        `Refusing to overwrite "${file.path}": the file exists and was not generated by ${PLUGIN_NAME}. Move it aside or point outDir at another directory.`,
        file.path,
      );
    }
    pending.push(file);
  }

  for (const file of pending) {
    fs.mkdirSync(path.dirname(file.path), { recursive: true });
    fs.writeFileSync(file.path, file.content);
    changed.push(file.path);
  }

  for (const stalePath of previous.keys()) {
    if (!next.has(stalePath)) {
      fs.rmSync(stalePath, { force: true });
      changed.push(stalePath);
    }
  }

  if (coldStart && outDir !== undefined) {
    for (const orphan of findGeneratedFiles(outDir)) {
      if (next.has(orphan) || previous.has(orphan)) continue;
      fs.rmSync(orphan, { force: true });
      changed.push(orphan);
    }
  }

  previous.clear();
  for (const [filePath, content] of next) {
    previous.set(filePath, content);
  }
  return changed;
}

function readSourceFiles(srcDir: string): string[] {
  let dirEntries: fs.Dirent[];
  try {
    dirEntries = fs.readdirSync(srcDir, { withFileTypes: true });
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code === "ENOENT") {
      throw new CodegenError(`Translation source directory does not exist: ${srcDir}`);
    }
    if (code === "ENOTDIR") {
      throw new CodegenError(`Translation source path is not a directory: ${srcDir}`);
    }
    throw new CodegenError(
      `Unable to read translation source directory "${srcDir}": ${(err as Error).message}`,
    );
  }

  return (
    dirEntries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
      .map((entry) => path.join(srcDir, entry.name))
      // Code-point order: locale-aware collation depends on the host ICU build and
      // would make the reference locale (and therefore the output) machine-specific.
      .sort()
  );
}

function pruneCache(cache: LocaleCache, sourceFiles: string[]): void {
  if (cache.size === 0) return;
  // Size alone is not a safe guard: one locale removed and another added in the
  // same window keeps the count equal while leaving a dead entry behind.
  const live = new Set(sourceFiles);
  for (const filePath of cache.keys()) {
    if (!live.has(filePath)) cache.delete(filePath);
  }
}

function statOrUndefined(filePath: string): fs.Stats | undefined {
  try {
    return fs.statSync(filePath);
  } catch {
    return undefined;
  }
}

function readFileIfExists(filePath: string): string | undefined {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw new CodegenError(`Unable to read "${filePath}": ${(err as Error).message}`, filePath);
  }
}

function isGeneratedContent(content: string): boolean {
  return content.slice(0, HEADER_SCAN_BYTES).includes(GENERATED_MARKER);
}

/** Files in `dir` that carry this plugin's header. Only reads each file's head. */
function findGeneratedFiles(dir: string): string[] {
  let dirEntries: fs.Dirent[];
  try {
    dirEntries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }

  const found: string[] = [];
  for (const entry of dirEntries) {
    if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
    const filePath = path.join(dir, entry.name);
    if (isGeneratedContent(readHead(filePath, HEADER_SCAN_BYTES))) found.push(filePath);
  }
  return found;
}

function readHead(filePath: string, length: number): string {
  let fd: number | undefined;
  try {
    fd = fs.openSync(filePath, "r");
    const buffer = Buffer.alloc(length);
    const read = fs.readSync(fd, buffer, 0, length, 0);
    return buffer.toString("utf8", 0, read);
  } catch {
    return "";
  } finally {
    if (fd !== undefined) fs.closeSync(fd);
  }
}

function parseEntry(key: string, value: string, filePath: string): TranslationEntry {
  const params: string[] = [];
  const parts: string[] = [];
  let last = 0;

  for (const match of value.matchAll(PLACEHOLDER)) {
    const index = match.index ?? 0;
    const literal = value.slice(last, index);
    validateBraceFree(key, literal, filePath);
    parts.push(escapeTemplateLiteral(literal));

    const param = match[1];
    if (param === undefined) {
      throw new CodegenError(
        `Invalid placeholder "${match[0]}" in "${key}" (${path.basename(filePath)}). Placeholders must be valid identifiers, e.g. {name}`,
        filePath,
      );
    }
    if (RESERVED_WORDS.has(param) || RESTRICTED_BINDINGS.has(param)) {
      throw new CodegenError(
        `Placeholder "{${param}}" in "${key}" (${path.basename(filePath)}) is not usable as a parameter name because "${param}" is reserved. Rename the placeholder`,
        filePath,
      );
    }
    if (!params.includes(param)) params.push(param);
    parts.push(`\${${param}}`);
    last = index + match[0].length;
  }

  const tail = value.slice(last);
  validateBraceFree(key, tail, filePath);
  parts.push(escapeTemplateLiteral(tail));

  return { key, params, template: parts.join("") };
}

function validateBraceFree(key: string, literal: string, filePath: string): void {
  if (literal.includes("{") || literal.includes("}")) {
    throw new CodegenError(
      `Unmatched "{" or "}" in "${key}" (${path.basename(filePath)})`,
      filePath,
    );
  }
}

/**
 * Escapes a literal segment for use inside a template literal. `${` needs no
 * handling here: `validateBraceFree` guarantees braces never reach this point.
 */
function escapeTemplateLiteral(value: string): string {
  return value.replace(
    NEEDS_ESCAPE,
    (char) => ESCAPE_MAP[char] ?? `\\u${char.charCodeAt(0).toString(16).padStart(4, "0")}`,
  );
}

function isValidIdentifier(name: string): boolean {
  return JS_IDENTIFIER.test(name) && !RESERVED_WORDS.has(name) && !RESTRICTED_BINDINGS.has(name);
}

function toIdentifier(name: string): string {
  if (isValidIdentifier(name)) return name;
  const parts = name.split(/[^A-Za-z0-9_$]+/).filter(Boolean);
  const camel = parts
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
  if (isValidIdentifier(camel)) return camel;
  return camel.length > 0 ? `_${camel}` : "_";
}

function validateLocaleName(locale: string, filePath: string): void {
  if (!LOCALE_NAME.test(locale)) {
    throw new CodegenError(
      `Invalid locale filename "${path.basename(filePath)}". Locale names may only contain letters, numbers, and underscores`,
      filePath,
    );
  }
}

function validateIdentifiers(locales: ParsedLocale[]): void {
  const seen = new Map<string, ParsedLocale>();
  for (const locale of locales) {
    const clash = seen.get(locale.identifier);
    if (clash) {
      throw new CodegenError(
        `"${path.basename(clash.filePath)}" and "${path.basename(locale.filePath)}" map to the same import identifier "${locale.identifier}"`,
        locale.filePath,
      );
    }
    seen.set(locale.identifier, locale);
  }
}

function validateParity(locales: ParsedLocale[], reference: ParsedLocale): void {
  const referenceName = path.basename(reference.filePath);

  for (const locale of locales) {
    if (locale === reference) continue;
    for (const [key, expected] of reference.entriesByKey) {
      const entry = locale.entriesByKey.get(key);
      if (entry === undefined) {
        throw new CodegenError(
          `${path.basename(locale.filePath)} is missing translation key "${key}" present in ${referenceName}`,
          locale.filePath,
        );
      }
      if (!sameParams(expected.params, entry.params)) {
        throw new CodegenError(
          `Placeholders for "${key}" in ${path.basename(locale.filePath)} (${formatParams(entry.params)}) do not match ${referenceName} (${formatParams(expected.params)})`,
          locale.filePath,
        );
      }
    }
    for (const key of locale.entriesByKey.keys()) {
      if (!reference.entriesByKey.has(key)) {
        throw new CodegenError(
          `"${key}" in ${path.basename(locale.filePath)} is not present in ${referenceName}`,
          locale.filePath,
        );
      }
    }
  }
}

/** Set comparison: placeholder order may differ between locales, the set may not. */
function sameParams(a: string[], b: string[]): boolean {
  if (a.length !== b.length) return false;
  return a.every((param) => b.includes(param));
}

function formatParams(params: string[]): string {
  return params.length > 0 ? `{${params.join(", ")}}` : "(none)";
}

function keyLabel(key: string): string {
  return isValidIdentifier(key) ? key : JSON.stringify(key);
}

function propertyKeyLabel(key: string): string {
  if (JS_IDENTIFIER.test(key)) return key;
  // A bare numeric key must round-trip: `0123` is an octal literal (illegal in a
  // module) and `09` is an illegal decimal, and both would rename the property.
  if (NUMERIC_KEY.test(key) && String(Number(key)) === key) return key;
  return JSON.stringify(key);
}

/**
 * Parameters are ordered alphabetically rather than by appearance. Placeholder
 * sets are identical across locales (enforced by `validateParity`), so every
 * locale derives the same signature — a translation may reorder its placeholders
 * without silently swapping arguments, and adding a locale that sorts first can
 * never reshuffle existing call sites.
 */
function signature(entry: TranslationEntry): string {
  return [...entry.params]
    .sort()
    .map((param) => `${param}: string`)
    .join(", ");
}

function buildLocaleFile(locale: ParsedLocale): string {
  const lines = [
    HEADER,
    "",
    'import type { Translations } from "./index.js";',
    "",
    "export default {",
    ...locale.entries.map(
      (entry) => `  ${keyLabel(entry.key)}: (${signature(entry)}) => \`${entry.template}\`,`,
    ),
    "} satisfies Translations;",
    "",
  ];
  return lines.join("\n");
}

function buildIndexFile(locales: ParsedLocale[], reference: ParsedLocale): string {
  const lines = [
    HEADER,
    "",
    ...locales.map((locale) => `import ${locale.identifier} from "./${locale.locale}.js";`),
    "",
    `export type Locale = ${locales.map((locale) => JSON.stringify(locale.locale)).join(" | ")};`,
    "export type Translations = {",
    ...reference.entries.map(
      (entry) => `  ${keyLabel(entry.key)}: (${signature(entry)}) => string;`,
    ),
    "};",
    "export type Dictionary = Record<Locale, Translations>;",
    "",
    `export const dictionary: Dictionary = { ${locales
      .map((locale) => `${propertyKeyLabel(locale.locale)}: ${locale.identifier}`)
      .join(", ")} };`,
    "",
  ];
  return lines.join("\n");
}
